"""
Synthetic English null calibration for the non-parametric strategies.

This file is auto-generated by paper/scripts/generate_data.py
Data source: Peter Norvig's word frequency list (https://norvig.com/ngrams/)
Source provenance: paper/scripts/data_curation.json

STATISTIC_NULL holds the (median, q99) of each raw statistic per length
bucket; TAIL_GRID lists the upper-tail probabilities of the tail tables.

Do not edit this file manually.
"""

# fmt: off
STATISTIC_NULL = {
    "cross_parsing": (
        (0.222222, 0.4),
        (0.2, 0.318182),
        (0.196429, 0.277778),
        (0.194444, 0.246753),
    ),
    "primed_compression": (
        (0.692308, 1.0),
        (0.586207, 0.823529),
        (0.532258, 0.69697),
        (0.511628, 0.628571),
    ),
    "ngram_rank": (
        (0.255471, 0.43004),
        (0.291745, 0.411021),
        (0.318515, 0.415132),
        (0.347126, 0.413844),
    ),
    "permutation_test": (
        (-1.010285, -0.157577),
        (-1.019313, -0.453155),
        (-1.020002, -0.602165),
        (-1.017251, -0.748231),
    ),
}
TAIL_GRID = (0.5, 0.25, 0.1, 0.05, 0.025, 0.01, 0.005, 0.0025, 0.001)
# fmt: on
