"""
Synthetic English null calibration for the non-parametric strategies.

This file is auto-generated by paper/scripts/generate_data.py
Data source: Peter Norvig's word frequency list (https://norvig.com/ngrams/)
Source provenance: paper/scripts/data_curation.json

STATISTIC_NULL holds the (median, q99) of each raw statistic per length
bucket; TAIL_GRID lists the upper-tail probabilities of the tail tables.
SCORE_NULL_TAILS holds, per strategy, the null score quantile at one
minus each TAIL_GRID probability (empty when no null text is applicable).

Do not edit this file manually.
"""

# fmt: off
STATISTIC_NULL = {
    "cross_parsing": (
        (0.222222, 0.4),
        (0.2, 0.318182),
        (0.196429, 0.277778),
        (0.194444, 0.246753),
    ),
    "primed_compression": (
        (0.692308, 1.0),
        (0.586207, 0.823529),
        (0.532258, 0.69697),
        (0.511628, 0.628571),
    ),
    "ngram_rank": (
        (0.255471, 0.43004),
        (0.291745, 0.411021),
        (0.318515, 0.415132),
        (0.347126, 0.413844),
    ),
    "permutation_test": (
        (-1.010285, -0.157577),
        (-1.019313, -0.453155),
        (-1.020002, -0.602165),
        (-1.017251, -0.748231),
    ),
}
TAIL_GRID = (0.5, 0.25, 0.1, 0.05, 0.025, 0.01, 0.005, 0.0025, 0.001)
SCORE_NULL_TAILS = {
    "control_characters": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "local_anomaly": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "pattern_matching": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.65, 0.65),
    "entropy_based": (0.014753, 0.046463, 0.07141, 0.08421, 0.1, 0.112334, 0.125348, 0.140207, 0.189206),
    "vowel_ratio": (0.0, 0.0, 0.0, 0.0, 0.25, 0.25, 0.5, 0.5, 0.75),
    "keyboard_pattern": (0.0, 0.0, 0.0, 0.0, 0.308333, 0.440741, 0.533333, 0.575, 0.666667),
    "markov_chain": (0.0, 0.185824, 0.320815, 0.425009, 0.542722, 0.697678, 0.794694, 0.862766, 0.950016),
    "ngram_frequency": (0.0, 0.057143, 0.190476, 0.285714, 1.0, 1.0, 1.0, 1.0, 1.0),
    "word_lookup": (0.0, 0.061224, 0.117647, 0.2, 0.333333, 0.5, 0.5, 1.0, 1.0),
    "symbol_ratio": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "repetition": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6),
    "hex_string": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "mojibake": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "pronounceability": (0.0, 0.0, 0.0, 0.0, 0.84, 1.0, 1.0, 1.0, 1.0),
    "unicode_script": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "bigram_probability": (0.0, 0.0, 0.0, 0.0, 0.006873, 0.015873, 0.034483, 0.064516, 0.153846),
    "letter_position": (0.0, 0.0, 0.0, 0.0, 0.266667, 0.75, 0.75, 0.75, 0.75),
    "consonant_sequence": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "vowel_pattern": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "letter_frequency": (0.0, 0.0, 0.0, 0.226171, 0.403415, 0.432751, 0.45125, 0.467136, 0.492151),
    "rare_trigram": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "function_word_density": (0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.3, 0.8),
    "affix_detection": (0.0, 0.0, 0.39375, 0.461905, 0.495918, 0.536957, 0.561111, 0.591304, 0.6375),
    "zipf_conformity": (0.0, 0.028125, 0.225, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45),
    "word_collocation": (0.45, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6),
    "log_likelihood_ratio": (0.058985, 0.065151, 0.074841, 0.085872, 0.098132, 0.121226, 0.145724, 0.182198, 0.23012),
    "word_anomaly": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.042553, 0.117647),
    "keyboard_adjacency": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "cross_parsing": (0.047426, 0.073205, 0.11013, 0.148047, 0.191836, 0.245238, 0.294038, 0.372424, 0.440628),
    "primed_compression": (0.045353, 0.072139, 0.117039, 0.154768, 0.193391, 0.268941, 0.282845, 0.387381, 0.453262),
    "ngram_rank": (0.056258, 0.087533, 0.126316, 0.16044, 0.199395, 0.248749, 0.289653, 0.33385, 0.400297),
    "permutation_test": (0.047188, 0.072872, 0.111283, 0.145019, 0.180789, 0.24191, 0.286923, 0.33656, 0.394933),
}
# fmt: on
