"""Reproduce the frozen study: python -m paper.study.run."""

import argparse
import csv
import gzip
import io
import json
import math
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from .data import ROOT, digest, prepare, write_json
from .detectors import CALIBRATED, DEFAULTS, FOLDS, make_model, threshold
from .metrics import summarize


def evaluate(docs: list, rows: list) -> tuple:
    predictions = []
    calibrations = []

    def predict(
        model: Any,
        selected: list,
        method: str,
        cutoff: float,
        experiment: str,
        fold: str,
    ) -> None:
        for row in selected:
            score, applicable, status = model.score(row["text"])
            if not math.isfinite(score) or score < 0:
                raise ValueError("Invalid score from " + method)
            decision = int(applicable and score >= cutoff)
            predictions.append(
                {
                    **{
                        k: row[k]
                        for k in (
                            "id",
                            "doc_id",
                            "family",
                            "domain",
                            "label",
                            "view",
                        )
                    },
                    "experiment": experiment,
                    "fold": fold,
                    "method": method,
                    "score": score,
                    "applicable": int(applicable),
                    "native_status": status,
                    "threshold": cutoff,
                    "predicted": decision,
                }
            )

    for method in DEFAULTS:
        print("Scoring defaults:", method, flush=True)
        model = make_model(method, [])
        predict(model, rows, method, 0.5, "default", "all")
    primary = [row for row in rows if row["view"] == 400]
    for test_family, train_family, valid_family in FOLDS:
        training = [
            doc["text"][:100000]
            for doc in docs
            if doc["family"] == train_family
        ]
        validation = [r for r in primary if r["family"] == valid_family]
        test = [r for r in primary if r["label"] or r["family"] == test_family]
        for method in CALIBRATED:
            print("Scoring calibrated:", test_family, method, flush=True)
            model = make_model(method, training)
            scores = [model.score(row["text"]) for row in validation]
            cutoff = threshold(scores)
            calibrations.append(
                {
                    "method": method,
                    "test_family": test_family,
                    "train_family": train_family,
                    "validation_family": valid_family,
                    "validation_n": len(scores),
                    "threshold": cutoff,
                    "validation_fpr": sum(
                        applicable and score >= cutoff
                        for score, applicable, _ in scores
                    )
                    / len(scores),
                    "above_bounded_score_range": (
                        not method.startswith("char_") and cutoff > 1
                    ),
                    "training_doc_ids": [
                        d["doc_id"]
                        for d in docs
                        if d["family"] == train_family
                    ],
                    "validation_doc_ids": sorted(
                        {r["doc_id"] for r in validation}
                    ),
                    "test_doc_ids": sorted({r["doc_id"] for r in test}),
                }
            )
            predict(model, test, method, cutoff, "calibrated", test_family)
    return predictions, calibrations


def save_predictions(path: Path, predictions: list) -> None:
    text = io.StringIO(newline="")
    writer = csv.DictWriter(text, fieldnames=list(predictions[0]))
    writer.writeheader()
    writer.writerows(predictions)
    path.write_bytes(gzip.compress(text.getvalue().encode(), mtime=0))


def code_manifest() -> Dict[str, str]:
    files = list(ROOT.glob("*.py")) + [
        ROOT / "protocol.md",
        ROOT / "sources.json",
    ]
    package = ROOT.parents[1] / "pygarble"
    files += sorted(package.rglob("*.py"))
    files += [package / "data/manifest.json"]
    return {
        str(path.relative_to(ROOT.parents[1])): digest(path.read_bytes())
        for path in sorted(files)
    }


def report(output: Path, summary: list, calibrations: list) -> None:
    lines = [
        "# Published-corpus results",
        "",
        "Generated by `python -m paper.study.run`. Source labels "
        "are inherited;",
        "no new human label audit was performed. See `../protocol.md`.",
        "",
        "## Default decisions at 400 characters",
        "",
        "FPR columns are descriptive rates within each source document.",
        "The 38 positive prefixes are documents; control blocks "
        "are clustered.",
        "",
        "| Method | Detected / positives | Recall (conditional "
        "Wilson 95%) | KJV FPR | NET FPR | Secreta FPR | Wiki FPR |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in summary:
        if row["experiment"] != "default" or row["view"] != 400:
            continue
        lo, hi = row["recall_wilson95_conditional"]
        rates = row["by_negative_document"]
        values = [
            "{:.1%}".format(rates[d]["fpr"])
            for d in ("kjv", "net", "secreta", "wiki")
        ]
        lines.append(
            "| {} | {}/{} | {:.1%} ({:.1%}–{:.1%}) | {} |".format(
                row["method"],
                row["true_positives"],
                row["positive_documents"],
                row["recall"],
                lo,
                hi,
                " | ".join(values),
            )
        )
    lines += [
        "",
        "## Calibration transfer at 400 characters",
        "",
        "Thresholds use only meaningful validation text at an empirical 1%",
        "FPR budget. Test rates need not meet that budget. Positive documents",
        "repeat across folds and must not be pooled as independent samples.",
        "",
        "| Held-out family | Method | Recall | Macro document "
        "test FPR | Validation FPR | Threshold |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    lookup = {(r["method"], r["test_family"]): r for r in calibrations}
    for row in summary:
        if row["experiment"] != "calibrated":
            continue
        cal = lookup[(row["method"], row["fold"])]
        lines.append(
            "| {} | {} | {:.1%} | {:.1%} | {:.1%} | {:.8g} |".format(
                row["fold"],
                row["method"],
                row["recall"],
                row["macro_document_fpr"],
                cal["validation_fpr"],
                cal["threshold"],
            )
        )
    lines += [
        "",
        "## Interpretation limits",
        "",
        "- Only 38 released positive documents and four English "
        "control documents.",
        "- No new human audit; supplied classes may not match a "
        "deployment task.",
        "- Historical spelling is meaningful but outside "
        "ordinary modern-English expectations.",
        "- Source/class confounding and shared collection conditions remain.",
        "- No claim of a population 1% FPR guarantee or semantic "
        "understanding.",
        "- Uncertainty intervals do not account for unknown "
        "participant dependencies.",
        "- Complete sensitivity, coverage and paired differences "
        "are in `summary.json`.",
        "- Raw predictions are in `predictions.csv.gz`; no "
        "comparison text is redistributed.",
        "- Timing describes this harness's scoring path and this "
        "machine only.",
        "",
    ]
    (output / "report.md").write_text("\n".join(lines), encoding="utf-8")


def benchmark(cache: Path, output: Path) -> None:
    results = []
    for method in DEFAULTS + ("char_bigram", "char_trigram"):
        measurements = {}
        for mode in ("timing", "memory"):
            command = [
                sys.executable,
                "-m",
                "paper.study.runtime",
                "--cache",
                str(cache),
                "--method",
                method,
                "--mode",
                mode,
            ]
            result = subprocess.run(
                command, check=True, capture_output=True, text=True
            )
            measurements.update(json.loads(result.stdout))
        results.append({"method": method, **measurements})
        print("Benchmarked:", method, flush=True)
    write_json(output / "runtime.json", results)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, default=ROOT / ".cache")
    parser.add_argument("--output", type=Path, default=ROOT / "results")
    parser.add_argument("--prepare-only", action="store_true")
    parser.add_argument("--skip-timing", action="store_true")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    docs, rows = prepare(args.cache, args.output)
    if args.prepare_only:
        return
    write_json(args.output / "code-manifest.json", code_manifest())
    predictions, calibrations = evaluate(docs, rows)
    save_predictions(args.output / "predictions.csv.gz", predictions)
    summary = summarize(predictions)
    write_json(args.output / "summary.json", summary)
    write_json(args.output / "calibration.json", calibrations)
    report(args.output, summary, calibrations)
    import pygarble

    write_json(
        args.output / "environment.json",
        {
            "python": sys.version,
            "platform": platform.platform(),
            "machine": platform.machine(),
            "pygarble_version": pygarble.__version__,
            "library_git_revision": subprocess.check_output(
                ["git", "rev-parse", "HEAD"], text=True
            ).strip(),
            "study_protocol_sha256": digest(
                (ROOT / "protocol.md").read_bytes()
            ),
            "paid_services_used": False,
            "new_human_label_audit": False,
            "label_origin": "published source classifications",
            "run_timestamp_utc": datetime.now(timezone.utc).isoformat(),
        },
    )
    if not args.skip_timing:
        benchmark(args.cache, args.output)
    print("Results:", args.output, flush=True)


if __name__ == "__main__":
    main()
