#!/usr/bin/env python3
"""
Data generation script for pygarble.

Downloads pinned word frequency data from Peter Norvig's collection
and generates embedded lookup tables for the library.

Data source: https://norvig.com/ngrams/
See scripts/data_curation.json for source attribution and provenance.

This script should be run at development time, not at runtime.
The generated files are committed to the repository.
"""

import argparse
import hashlib
import json
import math
import tempfile
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Set, Tuple

# URLs for data sources
NORVIG_WORD_FREQ_URL = "https://norvig.com/ngrams/count_1w.txt"

# Output paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_DIR = PROJECT_ROOT / "pygarble" / "data"

# Log probability for unseen bigrams, shared by the .py and .json tables
DEFAULT_LOG_PROB = -10.0


def download_word_frequencies(url: str) -> Dict[str, int]:
    """Download word frequency data from Norvig's site."""
    print(f"Downloading word frequencies from {url}...")

    with urllib.request.urlopen(url, timeout=30) as response:
        content = response.read().decode("utf-8")

    word_freq = {}
    for line in content.strip().split("\n"):
        parts = line.strip().split("\t")
        if len(parts) == 2:
            word, count = parts
            word = word.lower().strip()
            # Only include alphabetic words
            if word.isalpha() and len(word) >= 2:
                word_freq[word] = int(count)

    print(f"  Downloaded {len(word_freq)} words")
    return word_freq


def generate_english_words(
    word_freq: Dict[str, int], max_words: int = 50000
) -> Set[str]:
    """
    Generate set of common English words.

    Uses top N words by frequency, filtered for quality.
    """
    print(f"Generating English word set (top {max_words})...")

    # Sort by frequency and take top N
    sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)

    words = set()
    for word, freq in sorted_words[:max_words]:
        # Additional quality filters
        if len(word) >= 2 and word.isalpha():
            words.add(word)

    print(f"  Generated {len(words)} words")
    return words


def compute_bigram_probabilities(
    word_freq: Dict[str, int]
) -> Dict[str, float]:
    """
    Compute log-probability transition matrix for character bigrams.

    Uses Laplace smoothing to handle unseen bigrams.
    Returns log probabilities for numerical stability.
    """
    print("Computing bigram transition probabilities...")

    # Count all bigrams weighted by word frequency
    bigram_counts: Dict[Tuple[str, str], int] = defaultdict(int)
    char_counts: Dict[str, int] = defaultdict(int)

    # Process words weighted by their frequency
    for word, freq in word_freq.items():
        word = word.lower()
        # Add word boundaries
        padded = " " + word + " "
        for i in range(len(padded) - 1):
            c1, c2 = padded[i], padded[i + 1]
            if c1.isalpha() or c1 == " ":
                if c2.isalpha() or c2 == " ":
                    bigram_counts[(c1, c2)] += freq
                    char_counts[c1] += freq

    # All possible characters (26 letters + space)
    chars = " abcdefghijklmnopqrstuvwxyz"
    vocab_size = len(chars)

    # Compute log probabilities with Laplace smoothing
    bigram_log_probs = {}
    smoothing = 1  # Laplace smoothing parameter

    for c1 in chars:
        total = char_counts.get(c1, 0) + smoothing * vocab_size
        for c2 in chars:
            count = bigram_counts.get((c1, c2), 0) + smoothing
            prob = count / total
            log_prob = math.log(prob)
            bigram_log_probs[c1 + c2] = round(log_prob, 6)

    print(f"  Generated {len(bigram_log_probs)} bigram probabilities")
    return bigram_log_probs


def compute_trigram_frequencies(
    word_freq: Dict[str, int], top_n: int = 2000
) -> Set[str]:
    """
    Compute set of most common character trigrams.
    """
    print(f"Computing top {top_n} trigram frequencies...")

    trigram_counts: Counter = Counter()

    for word, freq in word_freq.items():
        word = word.lower()
        if len(word) >= 3:
            for i in range(len(word) - 2):
                trigram = word[i : i + 3]
                if trigram.isalpha():
                    trigram_counts[trigram] += freq

    # Get top N trigrams
    top_trigrams = set(t for t, _ in trigram_counts.most_common(top_n))

    print(f"  Generated {len(top_trigrams)} common trigrams")
    return top_trigrams


def write_words_file(words: Set[str], filepath: Path) -> None:
    """Write English words as a Python module."""
    print(f"Writing words to {filepath}...")

    # Sort for deterministic output
    sorted_words = sorted(words)

    content = '''"""
English word set for garble detection.

This file is auto-generated by scripts/generate_data.py
Data source: Peter Norvig's word frequency list (https://norvig.com/ngrams/)
Source provenance: scripts/data_curation.json

Do not edit this file manually.
"""

# fmt: off
ENGLISH_WORDS = frozenset({
'''

    # Write words in chunks for readability
    chunk_size = 10
    for i in range(0, len(sorted_words), chunk_size):
        chunk = sorted_words[i : i + chunk_size]
        line = "    " + ", ".join(f'"{w}"' for w in chunk) + ","
        content += line + "\n"

    content += """})
# fmt: on
"""

    filepath.write_text(content, encoding="utf-8")
    print(
        (
            "  Written "
            f"{len(words)}"
            " words ("
            f"{filepath.stat().st_size / 1024:.1f}"
            " KB)"
        )
    )


def write_bigrams_file(bigram_probs: Dict[str, float], filepath: Path) -> None:
    """Write bigram probabilities as a Python module."""
    print(f"Writing bigrams to {filepath}...")

    content = (
        '''"""
Character bigram log-probabilities for Markov chain garble detection.

This file is auto-generated by scripts/generate_data.py
Data source: Peter Norvig's word frequency list (https://norvig.com/ngrams/)
Source provenance: scripts/data_curation.json

Log probabilities are used for numerical stability.
Sum transition log scores to obtain the text log likelihood.

Do not edit this file manually.
"""

# Default log probability for unseen bigrams (very unlikely)
'''
        f"DEFAULT_LOG_PROB = {DEFAULT_LOG_PROB!r}\n"
        """
# fmt: off
BIGRAM_LOG_PROBS = {
"""
    )

    # Sort for deterministic output
    sorted_bigrams = sorted(bigram_probs.items())

    # Write in chunks
    chunk_size = 8
    for i in range(0, len(sorted_bigrams), chunk_size):
        chunk = sorted_bigrams[i : i + chunk_size]
        pairs = [f'"{k}": {v}' for k, v in chunk]
        content += "    " + ", ".join(pairs) + ",\n"

    content += """}
# fmt: on
"""

    filepath.write_text(content, encoding="utf-8")
    print(
        (
            "  Written "
            f"{len(bigram_probs)}"
            " bigrams ("
            f"{filepath.stat().st_size / 1024:.1f}"
            " KB)"
        )
    )


def write_trigrams_file(trigrams: Set[str], filepath: Path) -> None:
    """Write common trigrams as a Python module."""
    print(f"Writing trigrams to {filepath}...")

    sorted_trigrams = sorted(trigrams)

    content = '''"""
Common English character trigrams for garble detection.

This file is auto-generated by scripts/generate_data.py
Data source: Peter Norvig's word frequency list (https://norvig.com/ngrams/)
Source provenance: scripts/data_curation.json

Do not edit this file manually.
"""

# fmt: off
COMMON_TRIGRAMS = frozenset({
'''

    # Write in chunks
    chunk_size = 15
    for i in range(0, len(sorted_trigrams), chunk_size):
        chunk = sorted_trigrams[i : i + chunk_size]
        line = "    " + ", ".join(f'"{t}"' for t in chunk) + ","
        content += line + "\n"

    content += """})
# fmt: on
"""

    filepath.write_text(content, encoding="utf-8")
    print(
        (
            "  Written "
            f"{len(trigrams)}"
            " trigrams ("
            f"{filepath.stat().st_size / 1024:.1f}"
            " KB)"
        )
    )


def write_json(payload: object, filepath: Path) -> None:
    """Byte-reproducible JSON: sorted keys, compact, ASCII, final newline."""
    filepath.write_text(
        json.dumps(
            payload, ensure_ascii=True, sort_keys=True, separators=(",", ":")
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source", type=Path, help="Pinned count_1w.txt; downloads if omitted"
    )
    parser.add_argument("--output-dir", type=Path, default=DATA_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify reproducible files without writing",
    )
    args = parser.parse_args()
    curation_path = SCRIPT_DIR / "data_curation.json"
    curation = json.loads(curation_path.read_text())
    if args.source:
        raw = args.source.read_bytes()
    else:
        with urllib.request.urlopen(
            curation["source_url"], timeout=30
        ) as response:
            raw = response.read()
    if hashlib.sha256(raw).hexdigest() != curation["source_sha256"]:
        raise ValueError(
            "source checksum mismatch; review provenance before updating"
        )
    word_freq = {}
    for line in raw.decode("utf-8").splitlines():
        word, count = line.split("\t")
        if word.isalpha() and len(word) >= 2:
            word_freq[word] = int(count)
    words = generate_english_words(word_freq, curation["max_words"])
    words.difference_update(curation["exclude_words"])
    words.update(curation["include_words"])
    bigrams = compute_bigram_probabilities(word_freq)
    trigrams = compute_trigram_frequencies(word_freq, curation["top_trigrams"])
    with tempfile.TemporaryDirectory() as temporary:
        directory = Path(temporary)
        write_words_file(words, directory / "words.py")
        write_bigrams_file(bigrams, directory / "bigrams.py")
        write_trigrams_file(trigrams, directory / "trigrams.py")
        write_json(sorted(words), directory / "words.json")
        write_json(
            {"default_log_prob": DEFAULT_LOG_PROB, "log_probs": bigrams},
            directory / "bigrams.json",
        )
        write_json(sorted(trigrams), directory / "trigrams.json")
        manifest = {
            "model_version": "english-v2",
            "source_url": curation["source_url"],
            "source_sha256": curation["source_sha256"],
            "curation_sha256": hashlib.sha256(
                curation_path.read_bytes()
            ).hexdigest(),
            "counts": {
                "words": len(words),
                "bigrams": len(bigrams),
                "trigrams": len(trigrams),
            },
            "files": {
                file.name: hashlib.sha256(file.read_bytes()).hexdigest()
                for file in sorted(directory.iterdir())
                if file.suffix in (".py", ".json")
                and file.name != "manifest.json"
            },
        }
        (directory / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        if not args.check:
            args.output_dir.mkdir(parents=True, exist_ok=True)
        for generated in sorted(directory.iterdir()):
            destination = args.output_dir / generated.name
            if args.check:
                if (
                    not destination.exists()
                    or generated.read_bytes() != destination.read_bytes()
                ):
                    raise ValueError(
                        f"generated artifact differs: {destination}"
                    )
            else:
                destination.write_bytes(generated.read_bytes())
    print(
        "Artifact verification passed" if args.check else "Artifacts generated"
    )


if __name__ == "__main__":
    main()
