"""Generate the strategy reference from the registry and option catalog."""

import argparse
import inspect
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pygarble.gibberish.ensemble import PROFILES
from pygarble.gibberish.options import PARAMETERS
from pygarble.gibberish.registry import STRATEGY_MAP, Strategy


def render() -> str:
    lines = [
        "Detection Strategies",
        "====================",
        "",
        "Generated by ``python scripts/update_strategy_docs.py``.",
        "",
        (
            f"There are {len(Strategy)} strategies. "
            "Language checks target English;"
        ),
        "meaningful Hindi and other non-English text may be flagged. Encoding",
        "and spoofing specialists report their own evidence independently.",
        "",
        "Scores are heuristics, not calibrated probabilities. See the README",
        "for profile selection, applicability, and evaluation limitations.",
        "",
        "Profiles",
        "--------",
        "",
    ]
    for profile, strategies in PROFILES.items():
        lines.append(
            f"* ``{profile}``: "
            + ", ".join(f"``{s.name}``" for s in strategies)
        )
    lines.extend(["", "Strategy settings", "-----------------", ""])
    for strategy in Strategy:
        cls = STRATEGY_MAP[strategy]
        module = inspect.getmodule(cls)
        description = (
            cls.__doc__
            or (module.__doc__ if module else "")
            or "English text heuristic."
        )
        description = description.strip().splitlines()[0]
        lines.extend(
            [strategy.name, "~" * len(strategy.name), "", description, ""]
        )
        options = PARAMETERS[cls.__name__]
        lines.extend(
            [
                "Settings: "
                + ", ".join(f"``{name}``" for name in options)
                + ".",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / "docs/strategies.rst"
    content = render()
    if args.check:
        if path.read_text() != content:
            raise ValueError("strategy documentation is stale")
    else:
        path.write_text(content)


if __name__ == "__main__":
    main()
